AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Venafi policy integration for AWS Private CA.
Resources:
  CertRequestLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: cert-request
      Runtime: go1.x
      CodeUri: ../request/
      Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      #TODO: get role from parameters
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/lambda-venafi-role'
      Environment:
        Variables:
          S3_BUCKET: cert-request-lambda
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:DeleteItem'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/CertPolicyTable'
      Events:
        ApiRequest:
          Type: Api
          Properties:
            Path: /request
            Method: POST
        ApiGet:
          Type: Api
          Properties:
            Path: /get/{certId}
            Method: ANY
  CertPolicyTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: CertPolicyTable
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1